version: '3.8'

services:
  news-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_system_app
    stdin_open: true
    tty: true
    environment:
      - NEWS_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
